name: Kaiser Optik
favicon: null
layout_spectrum: 0.024622933473438025
typography_spectrum: 0.02177638467401266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5972677422687411
  lightness: 0.5951598645187914
  saturation: 0.7874847629573196
  rhythmicContrast: 0.3485460055526346
purpose: []
