name: Kaiser Optik
favicon: null
layout_spectrum: 0.76127
typography_spectrum: 0.38405
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#084b85'
    - '#ffffff'
    - '#fec43b'
    - '#5c89af'
    - '#93b1ca'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
